-- MySQL Script generated by MySQL Workbench
-- Fri Jul 14 15:21:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema paybillsonline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema paybillsonline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `paybillsonline` ;
USE `paybillsonline` ;

-- -----------------------------------------------------
-- Table `paybillsonline`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybillsonline`.`suppliers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `email` VARCHAR(50) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `phone` VARCHAR(12) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `paybillsonline`.` suppliersbankcards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybillsonline`.` suppliersbankcards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `balance` DECIMAL(10,0) NOT NULL,
  ` supplier_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Supplier_Card_idx` (` supplier_id` ASC) VISIBLE,
  CONSTRAINT `FK_Supplier_Card`
    FOREIGN KEY (` supplier_id`)
    REFERENCES `paybillsonline`.`suppliers` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paybillsonline`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybillsonline`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(30) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `lastname` VARCHAR(10) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `email` VARCHAR(50) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `phone` VARCHAR(12) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `dob` DATETIME NULL DEFAULT NULL,
  `gender` TINYINT NULL DEFAULT NULL,
  `address` VARCHAR(100) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `username` VARCHAR(20) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `password` VARCHAR(20) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `paybillsonline`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybillsonline`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `price` DECIMAL(10,0) NULL DEFAULT NULL,
  `supplier_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Supplier_idx` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `FK_Supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `paybillsonline`.`suppliers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `paybillsonline`.`cabletv`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybillsonline`.`cabletv` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `package_name` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `price` DECIMAL(10,0) NOT NULL,
  `service_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Service_Cab_idx` (`service_id` ASC) VISIBLE,
  INDEX `FK_User_Cab_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_Service_Cab`
    FOREIGN KEY (`service_id`)
    REFERENCES `paybillsonline`.`services` (`id`),
  CONSTRAINT `FK_User_Cab`
    FOREIGN KEY (`user_id`)
    REFERENCES `paybillsonline`.`users` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paybillsonline`.`meterindex`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybillsonline`.`meterindex` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meter_reading_new` INT NOT NULL,
  `meter_date_new` DATETIME NOT NULL,
  `meter_reading_old` INT NOT NULL,
  `meter_date_old` DATETIME NOT NULL,
  `price` DECIMAL(10,0) NOT NULL,
  `service_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Service_idx` (`service_id` ASC) VISIBLE,
  INDEX `FK_User_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_Service`
    FOREIGN KEY (`service_id`)
    REFERENCES `paybillsonline`.`services` (`id`),
  CONSTRAINT `FK_User_Meter`
    FOREIGN KEY (`user_id`)
    REFERENCES `paybillsonline`.`users` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paybillsonline`.`bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybillsonline`.`bills` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `due_date` DATETIME NOT NULL,
  `amount` DECIMAL(10,0) NOT NULL,
  `status` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `create_id` INT NULL DEFAULT NULL,
  `approved_id` INT NULL DEFAULT NULL,
  `meter_cab_id` INT NULL DEFAULT NULL,
  `info` VARCHAR(100) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_User_Bill_idx` (`user_id` ASC) VISIBLE,
  INDEX `FK_Create_idx` (`create_id` ASC) VISIBLE,
  INDEX `FK_Approved_idx` (`approved_id` ASC) VISIBLE,
  INDEX `FK_Meter_idx` (`meter_cab_id` ASC) VISIBLE,
  CONSTRAINT `FK_Approved`
    FOREIGN KEY (`approved_id`)
    REFERENCES `paybillsonline`.`users` (`id`),
  CONSTRAINT `FK_Cab`
    FOREIGN KEY (`meter_cab_id`)
    REFERENCES `paybillsonline`.`cabletv` (`id`),
  CONSTRAINT `FK_Create`
    FOREIGN KEY (`create_id`)
    REFERENCES `paybillsonline`.`users` (`id`),
  CONSTRAINT `FK_Meter`
    FOREIGN KEY (`meter_cab_id`)
    REFERENCES `paybillsonline`.`meterindex` (`id`),
  CONSTRAINT `FK_User_Bill`
    FOREIGN KEY (`user_id`)
    REFERENCES `paybillsonline`.`users` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paybillsonline`.`userbankcard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybillsonline`.`userbankcard` (
  `int` INT NOT NULL AUTO_INCREMENT,
  `card_number` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `expiry_date` DATETIME NOT NULL,
  `holder_name` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `cvv` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `balance` DECIMAL(10,0) NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`int`),
  INDEX `FK_User_Card_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_User_Card`
    FOREIGN KEY (`user_id`)
    REFERENCES `paybillsonline`.`users` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paybillsonline`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybillsonline`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `payment_date` DATETIME NOT NULL,
  `payment_method` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `bill_id` INT NULL DEFAULT NULL,
  `userbankcard_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Bil_Pay_idx` (`bill_id` ASC) VISIBLE,
  INDEX `FK_Card_Pay_idx` (`userbankcard_id` ASC) VISIBLE,
  CONSTRAINT `FK_Bil_Pay`
    FOREIGN KEY (`bill_id`)
    REFERENCES `paybillsonline`.`bills` (`id`),
  CONSTRAINT `FK_Card_Pay`
    FOREIGN KEY (`userbankcard_id`)
    REFERENCES `paybillsonline`.`userbankcard` (`int`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `paybillsonline`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybillsonline`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rolecode` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `name` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `info` VARCHAR(100) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `rolecode_UNIQUE` (`rolecode` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3;


-- -----------------------------------------------------
-- Table `paybillsonline`.`user_authorization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybillsonline`.`user_authorization` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `screen_id` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `role_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `screen_id_UNIQUE` (`screen_id` ASC) VISIBLE,
  INDEX `FK_User_idx` (`user_id` ASC) VISIBLE,
  INDEX `FK_Role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FK_Role`
    FOREIGN KEY (`role_id`)
    REFERENCES `paybillsonline`.`roles` (`id`),
  CONSTRAINT `FK_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `paybillsonline`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2;


-- -----------------------------------------------------
-- Table `paybillsonline`.`userbankcardstransaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `paybillsonline`.`userbankcardstransaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transaction_type` VARCHAR(45) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  `amount` DECIMAL(10,0) NOT NULL,
  `transaction_date` DATETIME NOT NULL,
  `description` VARCHAR(100) COLLATE 'utf8mb3_unicode_ci' NULL DEFAULT NULL,
  `usercardbank_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_Card_Trans_idx` (`usercardbank_id` ASC) VISIBLE,
  CONSTRAINT `FK_Card_Trans`
    FOREIGN KEY (`usercardbank_id`)
    REFERENCES `paybillsonline`.`userbankcard` (`int`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
